title: Engo
email: harrison@theshoebridges.com
description: > # this means to ignore newlines until "baseurl:"
    An open-source 2D game engine written in Go following the Entity-Component-System paradigm.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://engoengine.github.io" # the base hostname & protocol for your site
github_username: EngoEngine

include: ['_pages', "_tutorials"]

# Build settings
markdown: kramdown
